language: rust
rust:
  - stable
  - beta
cache: cargo
before_script:
  - rustup component add clippy
script:
  # fail build job when encountering warnings
  - cargo clippy -- -D warnings
  - cargo test --verbose --all
